name: Build binaries on release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Change permission
      run: chmod +x install_analysistoolsts.sh
    - name: Build executable
      run: sudo ./install_analysistoolsts.sh local
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/submitty_count_ts
          build/submitty_diagnostics_ts