name: Build binaries on release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (aarch64)
      if: matrix.arch == 'aarch64'
      run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - name: Set CC / CXX (aarch64)
      if: matrix.arch == 'aarch64'
      run: |
        echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "CXX=aarch64-linux-gnu-g++" >> $GITHUB_ENV
    - name: Build executable
      run: bash build.sh
    - name: Duplicate executables (x86_64)
      if: matrix.arch == 'x86_64'
      run: |
        cp build/submitty_count_ts build/submitty_count_ts-x86_64
        cp build/submitty_diagnostics_ts build/submitty_diagnostics_ts-x86_64
    - name: Move executables (aarch64)
      if: matrix.arch == 'aarch64'
      run: |
        mv build/submitty_count_ts build/submitty_count_ts-aarch64
        mv build/submitty_diagnostics_ts build/submitty_diagnostics_ts-aarch64
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: build/submitty_*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/submitty_*
