name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cpp-check
        run: sudo apt-get install -y cppcheck
      - name: run cpp-check
        run: cppcheck src/

