name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Change permission
      run: chmod +x install_analysistoolsts.sh
    - name: Build executable
      run: sudo ./install_analysistoolsts.sh local
    - name: install dev dependencies
      run: python3 -m pip install -r requirements_dev.txt
    - name: run tests
      run: pytest
