name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build executable
      run: |
        cmake -S . -B build
        cmake --build build --parallel "$(nproc)"
    - name: install dev dependencies
      run: python3 -m pip install -r requirements_dev.txt --break-system-packages
    - name: run tests
      run: pytest
