name: Test

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Disable 17.x for now, see https://github.com/tree-sitter/node-tree-sitter/issues/102
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - run: npm run test
